### ISSUE TITLE
Casting whole class instead of individual properties

### ISSUE THREAD

**Issue by muratcorlu** [ddramone/json2tsmodel#6]
Nowadays I'm using [mongoose](https://mongoosejs.com/docs/guide.html) and I found its schema definition way very practical. So maybe we can try to simplify model casting approach for this package too.

So idea is, instead of

```ts
class User extends BaseModel {
  @Cast() id: string;
  @Cast() name: string;
  @Cast() active = false;
}
```

doing this:

```ts
@Cast()
class User extends BaseModel {
  id: string;
  name: string;
  active = false;
}
```

End of course, if you need to do some specific things per property, you should still be able to use `@Cast()` per property:

```ts
@Cast()
class User extends BaseModel {
  @Cast('_id') id: string;
  name: string;
  active = false;
}
```

Even if it's possible, we can automate to extending class in decorator. Just like this:

```ts
@Cast()
class User {
  id: string;
  name: string;
  active = false;
}
```

What do you think?

**Comment by ddramone** [comment]
For me having decorator near property (even tho most of the time it's repeated) is more readable, since you can always have some other properties that aren't coming from json, i.e. you don't want to cast back to json.

```
class MyModel {
   @Cast() jsonProperty: string;
   
   myProperty: string
}
```
